"""Explicit data acquisition and admission. No network calls at import time."""
CATALOG = [
    dict(id='ghcnh', title='NOAA GHCNh · станции', capability='PSV v1.1, QC, ветер, температура и давление; автономная подготовка', access='public_https', state='implemented', limitation='Архивная задержка явно моделируется; оперативная доступность не подтверждена.'),
    dict(id='local_observations', title='Станции и аэрология · JSONL', capability='Проверка контракта, времени и масок', access='local', state='implemented', limitation='Не создаёт отсутствующие профили; физическое качество проверяется отдельно.'),
    dict(id='satdump', title='SatDump · ваша release/1.2.2', capability='Родные dataset.json, product.cbor, каналы, hrpt30/dump46, отчёты приборов', access='local', state='native_transport_only', limitation='Проверяется совместимость структуры; DN/презентационные PNG не допускаются как K. МТВЗА требует калибровки и антенного оператора.'),
    dict(id='graphcast', title='GraphCast · статистики ERA5', capability='Загрузка mean/std с контрольными суммами; импорт существующим модулем', access='public_https', state='implemented_not_live_verified', limitation='Недостаточно для полного набора величин; fit_period требуется подтвердить.'),
    dict(id='noaa_isd', title='NOAA ISD · наземные наблюдения', capability='Загрузка годового CSV станции; чтение T, Td, ветра и MSLP с QC', access='public_https', state='implemented_not_live_verified', limitation='В архиве нет исторической задержки поступления. Высоты датчиков требуют проверки; осадки не раскладываются по часам.'),
    dict(id='era5_cds', title='ERA5 · CDS', capability='Проверяемый запрос и явная загрузка через cdsapi', access='credentials_and_license', state='implemented_not_live_verified', limitation='Нужен ключ вне репозитория и принятие условий CDS. Реанализ — цели/нормы, не заполнение пропусков оперативных входов.'),
    dict(id='satellite_manifest', title='Электро-Л / Арктика-М · GPTL', capability='Родные STAC и normalize_asset; чтение локального L2IR и проверка .download.json', access='local_existing_acquisition', state='native_raster_bridge', limitation='Загрузка остаётся существующему клиенту; поддержан явный L2IR. Геометрия/нормы должны быть проверены, L3 не приравнивается к исходным каналам.'),
    dict(id='arktika_worker', title='arktika-worker · численные продукты', capability='product.json + values.tif + quality.tif без повторного scale/offset; экспорт в JSONL', access='local', state='native_raster_bridge', limitation='Только channel с подтверждёнными единицами/временем. RGB/разности/assumed запрещены. Углы/размер пятна нужны до передачи модели.'),
]
