"""Explicit data acquisition and admission. No network calls at import time."""
CATALOG = [
    dict(id='local_observations', title='Станции и аэрология · JSONL', capability='Проверка контракта, времени и масок', access='local', state='implemented', limitation='Не создаёт отсутствующие профили; физическое качество проверяется отдельно.'),
    dict(id='satdump', title='SatDump release/1.2.2 · МСУ-МР / МТВЗА / МСУ-ГС', capability='CLI project_bridge: нативные dataset.json, product.cbor, времена, каналы и статусы', access='local', state='implemented_contract_bridge', limitation='Не калибрует сырые значения. hrpt30 и no_data не становятся физическими измерениями; антенная геометрия МТВЗА ещё требуется.'),
    dict(id='graphcast', title='GraphCast · статистики ERA5', capability='Загрузка mean/std с контрольными суммами; импорт существующим модулем', access='public_https', state='implemented_not_live_verified', limitation='Недостаточно для полного набора величин; fit_period требуется подтвердить.'),
    dict(id='noaa_isd', title='NOAA ISD · наземные наблюдения', capability='Загрузка годового CSV станции; чтение T, Td, ветра и MSLP с QC', access='public_https', state='implemented_not_live_verified', limitation='В архиве нет исторической задержки поступления. Высоты датчиков требуют проверки; осадки не раскладываются по часам.'),
    dict(id='era5_cds', title='ERA5 · CDS', capability='Проверяемый запрос и явная загрузка через cdsapi', access='credentials_and_license', state='implemented_not_live_verified', limitation='Нужен ключ вне репозитория и принятие условий CDS. Реанализ — цели/нормы, не заполнение пропусков оперативных входов.'),
    dict(id='satellite_manifest', title='Арктика-М · каталог / Электро-Л · физический экспорт', capability='CLI project_bridge: read-only catalog.sqlite; physical_bridge: проверенный GeoTIFF и геометрия в JSONL', access='local', state='implemented_contract_bridge', limitation='ARCM-only каталог не является загрузчиком Электро-Л. Требуется явная проверка каналов, калибровки и времени; детали в docs/PROJECT_COMPATIBILITY.md.'),
]
